//constants for homescreen
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='PRODUCT_LIST_FAIL';

///constants for productscreen
export const PRODUCT_INFO_REQUEST='PRODUCT_INFO_REQUEST';
export const PRODUCT_INFO_SUCCESS='PRODUCT_INFO_SUCCESS';
export const PRODUCT_INFO_FAIL='PRODUCT_INFO_FAIL';

///constant for cartscreen
export const CART_ITEM='CART_ITEM';
export const DELETE_CART_ITEM='DELETE_CART_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS='CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD='CART_SAVE_PAYMENT_METHOD';

//constants for signin
export const USER_SIGNIN_REQUEST="USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS="USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL="USER_SIGNIN_FAIL";
export const USER_SIGNOUT="USER_SIGNOUT";

//constants for register
export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL';

